### ISSUE TITLE
System.InvalidOperationException: 'Sequence contains more than one matching element'

### ISSUE THREAD

**Issue by DiegoVenancioVieira** [martasp/BlazorLiveReload#16]
In blazor-server

System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains more than one matching element
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RazorComponentsPreview.RuntimeComponentsGenerator.ReadAllFiles(List`1 razorFiles)
   at RazorComponentsPreview.RuntimeComponentsGenerator..ctor(IServiceCollection serviceCollection)
   at RazorComponentsPreview.RazorRuntimeCompilationExtensions.UseRazorComponentsRuntimeCompilation(IApplicationBuilder app)
   at BServer....Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\...\...\Startup.cs:line 109
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()

**Comment by Levvy055** [comment]
Having the same problem  using Net5 Blazor Server.

**Comment by tb-mtg** [comment]
Not sure if same but on .NET5 Blazor Server which also has project reference to a Razor Class Library (RCL) get exception:

> System.NullReferenceException: Object reference not set to an instance of an object.
   at RazorComponentsPreview.RuntimeComponentsGenerator.ReadAllFiles(List`1 razorFiles)
   at RazorComponentsPreview.RuntimeComponentsGenerator..ctor(IServiceCollection serviceCollection)
   at RazorComponentsPreview.RazorRuntimeCompilationExtensions.UseRazorComponentsRuntimeCompilation(IApplicationBuilder app)
